apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-01
  name: app-01
spec:
  template:
    spec:
      containers:
        - name: app-01
          image: crz2wyl7mwvm3vq.azurecr.io/app-01:90
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: staging