apiVersion: v1
kind: Secret
metadata:
  name: stable-argo-structure-cred
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  url: $GIT_URL
  name: stable-argo-structure
  type: git
  password: $GIT_PSWD
  username: $USER_NAME
---
apiVersion: v1
kind: Secret
metadata:
  name: stable-argo-structure-repos
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: $GIT_URL
